#Author: Balaji N 
#Date: 27-06-2023
#Description: This is reusable workflow for testing secrets testing

on:
  workflow_call:
    inputs:
      GitHubActionRunner:
        required: true
        type: string
        description: 'Pass the GitHub Action Runner for the worklow'
      
jobs:
  SecretsTesting:
    runs-on: ${{ inputs.GitHubActionRunner }}

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v3

    - name: Octo CLI Install
      uses: OctopusDeploy/install-octopus-cli-action@v3
      with:
        version: '*'
        
    - name: list-octopusdeploy-accounts
      env:
        OCTOPUS_API_KEY: ${{ secrets.OCTOPUS_DEPLOY_API_KEY }}
        OCTOPUS_URL: ${{ secrets.OCTOPUS_HOST_URL }}
        OCTOPUS_HOST: ${{ secrets.OCTOPUS_HOST_URL }}
        OCTOPUS_SPACE: ${{ secrets.OCTOPUS_SPACE_NAME }}
        #OCTOPUS_API_KEY: ${{ secrets.OCTOPUS_DEPLOY_API_KEY_REPO }}
        #OCTOPUS_URL: ${{ secrets.OCTOPUS_HOST_URL_REPO }}
        #OCTOPUS_HOST: ${{ secrets.OCTOPUS_HOST_URL_REPO }}
        #OCTOPUS_SPACE: ${{ secrets.OCTOPUS_SPACE_NAME_REPO }}
      run: |
        octopus project list
        
    - name: Delete Octopus Project
      run: |
        $ErrorActionPreference = "Stop";

        # Define working variables
        $octopusURL = "${{ secrets.OCTOPUS_HOST_URL }}"
        $octopusAPIKey = "${{ secrets.OCTOPUS_DEPLOY_API_KEY }}"
        $header = @{ "X-Octopus-ApiKey" = $octopusAPIKey }
        $spaceName = "${{ secrets.OCTOPUS_SPACE_NAME }}"
        $projectName = "HelloWorld"

        # Get space
        $space = (Invoke-RestMethod -Method Get -Uri "$octopusURL/api/spaces/all" -Headers $header) | Where-Object {$_.Name -eq $spaceName}

        # Get project
        $project = (Invoke-RestMethod -Method Get -Uri "$octopusURL/api/$($space.Id)/projects/all" -Headers $header) | Where-Object {$_.Name -eq $projectName}

        # Delete project
        Invoke-RestMethod -Method Delete -Uri "$octopusURL/api/$($space.Id)/projects/$($project.Id)" -Headers $header

    #- name: List Accounts
      #run: |
       #octo list-projects --server=${{ secrets.OCTOPUS_HOST_URL }} --apiKey=${{ secrets.OCTOPUS_DEPLOY_API_KEY }}  --space=${{ secrets.OCTOPUS_SPACE_NAME }}
