#Author: Balaji N 
#Date: 27-06-2023
#Description: This is reusable workflow for testing secrets testing

on:
  workflow_call:
    inputs:
      GitHubActionRunner:
        required: true
        type: string
        description: 'Pass the GitHub Action Runner for the worklow'
      
jobs:
  SecretsTesting:
    runs-on: ${{ inputs,GitHubActionRunner }}

    steps:
    - name: Checkout Repo
      uses: actions/checkout@V3

    - name: Octo CLI Installation
      uses: OctopusDeploy/Install-octopus-cli-action@V1
      with:
        version: latest
  
    - name: Revealing the Secrets
      run: |
        write-host "Printing the Secrets from the GitHub Organization Secret ${{ secrets.OCTOPUS_DEPLOY_API_KEY }}"
