#Author: Balaji N 
#Date: 27-06-2023
#Description: This is reusable workflow for testing secrets testing

on:
  workflow_call:
    inputs:
      GitHubActionRunner:
        required: true
        type: string
        description: 'Pass the GitHub Action Runner for the worklow'
      
jobs:
  SecretsTesting:
    runs-on: ${{ inputs.GitHubActionRunner }}

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v3

    - name: Octo CLI Installation
      uses: OctopusDeploy/install-octopus-cli-action@v3
      with:
        version: latest
  
    - name: List Accounts
      env:
        OCTOPUS_API_KEY: ${{ secrets.OCTOPUS_DEPLOY_API_KEY }}
        OCTOPUS_URL: ${{ secrets.OCTOPUS_HOST_URL }}
        OCTOPUS_HOST: ${{ secrets.OCTOPUS_HOST_URL }}
        OCTOPUS_SPACE: ${{ secrets.OCTOPUS_SPACE_NAME }}
      run: |
        octopus account list
